// NativeChessModuleProvider.mm
//
// Implements the ObjC class that RCTModuleProviders.mm (generated by codegen)
// expects to find at runtime for 'NativeChessModule'.
//
// Codegen generates:
//   @"NativeChessModule": @"NativeChessModuleProvider"
// and calls NSClassFromString(@"NativeChessModuleProvider") then
// -[instance getTurboModule:params] to get the C++ TurboModule.
//
// We satisfy that contract here by returning std::make_shared<NativeChessModule>
// directly from the C++ implementation in shared/.

#import <Foundation/Foundation.h>
#import <ReactCommon/RCTTurboModule.h>
#import <NativeChessModule.h>

@interface NativeChessModuleProvider : NSObject <RCTModuleProvider>
@end

@implementation NativeChessModuleProvider

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<facebook::react::NativeChessModule>(params.jsInvoker);
}

@end
